[package]
name = "tomato-clock"
version = "0.1.0"
edition = "2021"
description = "A simple tomato clock"

[package.metadata.bundle]
identifier = "com.elliot00.tomato-clock"
category = "Utility"

[dependencies]
iced = { version = "0.7", features = ["canvas", "tokio"] }
notify-rust = "4"
